### ISSUE TITLE
Bot Online but not Playing Moves

### ISSUE THREAD

**Issue by sjorsvanheuveln** [tailuge/bot-o-tron#3]
Hey there, thanks for the awesome script. I got my account verified and registered as bot now. My bot is currently online. It responds in the chat but it is not moving. Do I still need to do something?

**Comment by sjorsvanheuveln** [comment]
I don't know, did you put in that bug on purpose? And the bot is quite suicidal :D. I like it.

**Comment by tailuge** [comment]
Happy you like it's random playing style. Running fine right now. Let me know if you install a brain into it.

https://test-o-a.herokuapp.com/

**Comment by sjorsvanheuveln** [comment]
But that bug was on purpose!?
